#!/usr/bin/env python3
"""Install genuine pinned Prek hooks with documented canonical execution.

Install the owning pinned upstream checker implementations faithfully.
The helper transforms the real generated Prek pre-commit and pre-push scripts,
keeping their actual checkers, executables and arguments intact, then reconciles managed
Repro hooks. All integration controls use real tools/filesystem; no mocks.
"""
from __future__ import annotations
import argparse
import hashlib
import os
from pathlib import Path
import shutil
import stat
import subprocess
import sys
import tempfile

CONTRACT = "reprobuild.managed-hook.v1.pre-commit.434c2eeac4079591"
EXPORT = b"export PREK_NO_FAST_PATH=1\n"
GENERATED = b"# File generated by prek: https://github.com/j178/prek\n"
# Exact former owning Circom SDK-generated pre-commit 4.3.0 body only.
LEGACY_OWNED_SHA256 = "9b5cedf2a83c15d43bd428612097478fd9e293e257b502481824deaec20cd9b7"

def run(argv: list[str], cwd: Path) -> str:
    return subprocess.check_output(argv, cwd=cwd, text=True, stderr=subprocess.STDOUT).strip()

def native_install_environment(env: dict[str, str], git: str, root: Path, hooks: Path) -> dict[str, str]:
    # Native Prek refuses a nonempty hooksPath, then installs in common/hooks.
    # Override only this child command after proving that same owned destination.
    if any(key == "GIT_CONFIG_COUNT" or key == "GIT_CONFIG_PARAMETERS"
            or key.startswith(("GIT_CONFIG_KEY_", "GIT_CONFIG_VALUE_")) for key in env):
        raise RuntimeError("ambiguous inherited Git command configuration")
    common = Path(run([git, "rev-parse", "--path-format=absolute", "--git-common-dir"], root))
    default_hooks = common / "hooks"
    if default_hooks.is_symlink() or default_hooks.resolve() != hooks:
        raise RuntimeError("native default hooks differ from verified owning hooks")
    # main already validates effective ownership, including its narrowly
    # qualified registered-worktree relative-path repair before installation.
    child = env.copy()
    child["GIT_CONFIG_COUNT"] = "1"
    child["GIT_CONFIG_KEY_0"] = "core.hooksPath"
    child["GIT_CONFIG_VALUE_0"] = ""
    return child

def native_install_to_terminal(argv: list[str], root: Path, env: dict[str, str]) -> None:
    child = subprocess.Popen(argv, cwd=root, env=env)
    interruption = None
    while True:
        try:
            code = child.wait()
            break
        except (KeyboardInterrupt, InterruptedError) as error:
            if interruption is None:
                interruption = error
    if interruption is not None:
        raise interruption
    if code:
        raise subprocess.CalledProcessError(code, argv)

def selected_tool(name: str) -> str:
    found = shutil.which(name)
    if not found:
        raise RuntimeError(f"missing declared native tool: {name}")
    return str(Path(found).absolute())

# Entire genuine pinned native template, including whitespace and final newlines.
# Only its independently selected owning executable binding varies by native SDK.
NATIVE_TEMPLATE = b'#!/usr/bin/env bash\n# File generated by prek: https://github.com/j178/prek\n# ID: 182c10f181da4464a3eec51b83331688\n\n# Unset GIT_DIR to avoid git taking current directory as the git dir.\n# See:\n# https://github.com/pre-commit/pre-commit/issues/2295\n# https://www.spinics.net/lists/git/msg374197.html\nunset GIT_DIR\n\nARGS=(hook-impl --hook-type=pre-commit --script-version=3)\n\nHERE="$(cd "$(dirname "$0")" && pwd)"\nARGS+=(--hook-dir "$HERE" -- "$@")\nPREK="@OWNING_PREK_EXECUTABLE@"\n\n# Check if the full path to prek is executable, otherwise fallback to PATH\nif [ ! -x "$PREK" ]; then\n    PREK="prek"\nfi\n\nexec "$PREK" "${ARGS[@]}"\n\n'

def native_generated_body(prek: str, hook_type: str = "pre-commit") -> bytes:
    if hook_type not in ("pre-commit", "pre-push"):
        raise RuntimeError("unqualified native hook type")
    return NATIVE_TEMPLATE.replace(b"@OWNING_PREK_EXECUTABLE@", os.fsencode(prek)).replace(
        b"--hook-type=pre-commit", os.fsencode("--hook-type=" + hook_type))

def canonical_body(prek: str, hook_type: str = "pre-commit") -> bytes:
    native = native_generated_body(prek, hook_type)
    first, rest = native.split(b"\n", 1)
    return first + b"\n" + EXPORT + rest

def canonical_generated_body(body: bytes, prek: str, mode: int, hook_type: str = "pre-commit") -> bytes:
    if mode != 0o755 or body != native_generated_body(prek, hook_type):
        raise RuntimeError("unexpected exact owning native Prek hook body or mode")
    return canonical_body(prek, hook_type)

def validate_prior_owned_body(body: bytes, mode: int, prek: str) -> None:
    if mode != 0o755:
        raise RuntimeError("former owning local hook mode changed")
    if hashlib.sha256(body).hexdigest() == LEGACY_OWNED_SHA256:
        return
    if body not in (native_generated_body(prek), canonical_body(prek)):
        raise RuntimeError("unknown or modified owning local hook body")

KNOWN_MANAGED_BODIES = {
    "pre-commit": "06cfcb59c42b99e9432c469f6bce7dc4fa5b0fa7c6f4f4e0548a1161233cf576",
    "pre-commit.repro-managed": "598ed91d257d1d236de042e708bd239837e069b2ee6fd583cf6b2d121f294507",
    "pre-push": "f5084841c5edfe6bfdaba3ad55c142b87e4e93b725754de0af553b57709e5c29",
    "pre-push.repro-managed": "642c37aca860a03ee6e7c2d0f941bf6fbdd1202c9f356c4fe68bf3ad3bfe6da6",
}

# Exact immutable native Git sample templates: former host and both owning
# Git2.51.2 package outputs, independently qualified full bodies/generated0755.
# Git does not dispatch the .sample filename, even with its native0755 mode.
KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES = {
    "99925aa22f22eed1a7e63b88b3416f2ecf28a222f5b627dfd6396bb8ec1b9508",
    "f35ff977f07f76b61e0ebc047bf500793d22d95fbcf86c6ab95561b6ba339bc8",
    "7b9d5ae35b46834cbd02a674efcae68e76994e513058d825ecd65b7060d35c83",
}


def pre_push_inventory(hooks: Path, prek: str) -> dict[str, tuple[bytes, int]]:
    inventory = {}
    if not hooks.exists():
        return inventory
    for path in hooks.iterdir():
        if not path.name.startswith("pre-push"):
            continue
        expected = KNOWN_MANAGED_BODIES.get(path.name)
        if path.name == "pre-push.repro-local":
            expected = "6188abf9e8ab8ed0207f941e4c5f87533b764478bbac3581607c5d467bf475f5"
        sample = path.name == "pre-push.sample"
        if expected is None and not sample:
            raise RuntimeError(f"unknown pre-push hook entry: {path.name}")
        metadata = path.lstat()
        if not stat.S_ISREG(metadata.st_mode):
            raise RuntimeError(f"unowned pre-push hook type: {path.name}")
        body = path.read_bytes()
        mode = stat.S_IMODE(metadata.st_mode)
        digest = hashlib.sha256(body).hexdigest()
        qualified_body = digest in KNOWN_GIT_PRE_PUSH_SAMPLE_BODIES if sample else digest == expected
        if path.name == "pre-push.repro-local":
            qualified_body = qualified_body or body in (native_generated_body(prek, "pre-push"), canonical_body(prek, "pre-push"))
        if mode != 0o755 or not qualified_body:
            raise RuntimeError(f"modified pre-push hook body or mode: {path.name}")
        inventory[path.name] = (body, mode)
    return inventory

OWNING_DECLARATIONS = (
    ".pre-commit-config.yaml", ".editorconfig", "flake.nix", "flake.lock",
    "circom_bus_sdk_tools.nim", "tools/circom-bus-sdk/default.nix",
    "tools/circom-bus-sdk/package.nix", "tools/circom-primary-sdk/default.nix",
    "tools/install-canonical-hooks.py",
)

def owned_common_directory(git: str, root: Path) -> Path:
    # Git registration and primary-owned metadata establish shared-hook ownership.
    raw_common = Path(run([git, "rev-parse", "--git-common-dir"], root))
    lexical_common = raw_common if raw_common.is_absolute() else root / raw_common
    if lexical_common.is_symlink():
        raise RuntimeError("symlink Git common directory")
    common = lexical_common.resolve(strict=True)
    records = subprocess.check_output(
        [git, "worktree", "list", "--porcelain", "-z"], cwd=root
    ).split(b"\0\0")
    registered = []
    for record in records:
        fields = record.split(b"\0")
        if fields and fields[0].startswith(b"worktree "):
            registered.append(Path(os.fsdecode(fields[0][9:])))
    if not registered or not any(path.resolve() == root for path in registered):
        raise RuntimeError("owning worktree is not registered")
    primary = registered[0]
    if primary.is_symlink() or not primary.is_dir():
        raise RuntimeError("primary worktree is not an owned regular directory")
    primary = primary.resolve(strict=True)
    primary_git = primary / ".git"
    if primary_git.is_symlink() or not primary_git.is_dir() or primary_git.resolve() != common:
        raise RuntimeError("Git common directory does not belong to registered primary")
    git_dir = Path(run([git, "rev-parse", "--absolute-git-dir"], root))
    if git_dir.is_symlink() or not git_dir.is_dir():
        raise RuntimeError("owning Git metadata is not a regular directory")
    resolved_git_dir = git_dir.resolve(strict=True)
    if root == primary:
        if resolved_git_dir != common:
            raise RuntimeError("primary Git metadata differs from common directory")
    else:
        if resolved_git_dir.parent != common / "worktrees":
            raise RuntimeError("linked worktree metadata is outside owning common directory")
        marker = root / ".git"
        if marker.is_symlink() or not marker.is_file():
            raise RuntimeError("linked worktree registration is not a regular file")
        registration = resolved_git_dir / "gitdir"
        if registration.is_symlink() or not registration.is_file():
            raise RuntimeError("missing genuine linked-worktree registration")
        if Path(registration.read_text().strip()).resolve(strict=True) != marker.resolve(strict=True):
            raise RuntimeError("linked-worktree registration points elsewhere")
    for name in OWNING_DECLARATIONS:
        current, original = root / name, primary / name
        for path in (current, original):
            if path.is_symlink() or not path.is_file():
                raise RuntimeError(f"owning declaration is not regular: {name}")
        if current.read_bytes() != original.read_bytes():
            raise RuntimeError(f"primary/current owning declaration differs: {name}")
    return common

def atomic_write(path: Path, data: bytes, mode: int) -> None:
    descriptor, filename = tempfile.mkstemp(prefix=".canonical-prek-", dir=path.parent)
    temporary = Path(filename)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(data)
            stream.flush()
            os.fsync(stream.fileno())
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        if temporary.exists():
            temporary.unlink()

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repro", required=True, help="explicit measured matching managed-hook engine")
    parser.add_argument("--bootstrap-managed", action="store_true",
                        help="ownership-check and establish matching managed hooks before canonical installation")
    args = parser.parse_args()
    root = Path.cwd().resolve()
    git = selected_tool("git")
    prek = selected_tool("prek")
    repro = Path(args.repro).absolute()
    if not repro.is_file() or not os.access(repro, os.X_OK):
        raise RuntimeError("missing selected matching Repro executable")
    if Path(run([git, "rev-parse", "--show-toplevel"], root)).resolve() != root:
        raise RuntimeError("run from actual owning repository root")
    if not (root / ".pre-commit-config.yaml").is_file():
        raise RuntimeError("missing owning portable standard config")
    if run([prek, "--version"], root) != "prek 0.2.17":
        raise RuntimeError("unqualified native Prek version")
    if run([str(repro), "hooks", "protocol", "--require=2", "--hook-contract=" + CONTRACT], root) != "2":
        raise RuntimeError("matching managed hook protocol failed")
    common = owned_common_directory(git, root)
    hooks = common / "hooks"
    if hooks.is_symlink() or (hooks.exists() and not hooks.is_dir()):
        raise RuntimeError("own hooks directory is symlink or non-directory")
    configured = subprocess.run([git, "config", "--get", "core.hooksPath"], cwd=root, text=True, capture_output=True)
    if configured.returncode not in (0, 1):
        raise RuntimeError("cannot inspect own hook path")
    repair_registered_relative_path = False
    if configured.returncode == 0:
        raw = Path(configured.stdout.strip())
        scope = run([git, "config", "--show-scope", "--get", "core.hooksPath"], root).split()[0]
        repair_registered_relative_path = (
            str(raw) == ".git/hooks" and scope == "local" and not (root / ".git").is_dir()
        )
        resolved = (root / raw).resolve() if not raw.is_absolute() else raw.resolve()
        if resolved != hooks and not repair_registered_relative_path:
            raise RuntimeError("nonowning or unqualified hooks directory")
    actual_hooks = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
    if actual_hooks.is_symlink() or (
        actual_hooks.resolve() != hooks.resolve() and not repair_registered_relative_path
    ):
        raise RuntimeError("effective Git hooks path is not the owning directory")
    if actual_hooks.exists() and not actual_hooks.is_dir():
        raise RuntimeError("effective hooks path is non-directory")
    for name, expected_hash in KNOWN_MANAGED_BODIES.items():
        path = hooks / name
        if path.is_symlink():
            raise RuntimeError(f"unowned managed hook symlink: {name}")
        if path.exists():
            if not path.is_file():
                raise RuntimeError(f"unowned managed hook type: {name}")
            body = path.read_bytes()
            if name == "pre-commit" and not body.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
                validate_prior_owned_body(body, stat.S_IMODE(path.stat().st_mode), prek)
            elif hashlib.sha256(body).hexdigest() != expected_hash or stat.S_IMODE(path.stat().st_mode) != 0o755:
                raise RuntimeError(f"unknown or modified managed hook template: {name}")
    original_pre_push = pre_push_inventory(hooks, prek)

    env = os.environ.copy()
    env["PREK_NO_FAST_PATH"] = "1"
    env["REPROBUILD_REPRO"] = str(repro)
    # The owning config requires language_version system; Prek refuses
    # managed Python downloads. The locked SDK supplies native Python on PATH.
    existing = hooks / "pre-commit"
    if existing.is_symlink():
        raise RuntimeError("unowned existing pre-commit symlink")
    if existing.exists():
        if existing.is_symlink() or not existing.is_file():
            raise RuntimeError("unowned existing pre-commit hook shape")
        previous = existing.read_bytes()
        if not previous.startswith(b"#!/usr/bin/env sh\n# reprobuild hook dispatcher protocol=2\n"):
            validate_prior_owned_body(previous, stat.S_IMODE(existing.stat().st_mode), prek)
    preserved = hooks / "pre-commit.repro-local"
    preserved_before = None
    if preserved.is_symlink():
        raise RuntimeError("unowned preserved local hook symlink")
    if preserved.exists():
        if preserved.is_symlink() or not preserved.is_file():
            raise RuntimeError("unowned preserved local hook shape")
        preserved_before = preserved.read_bytes()
        validate_prior_owned_body(preserved_before, stat.S_IMODE(preserved.stat().st_mode), prek)
    backup = None
    if preserved_before is not None and preserved_before != canonical_body(prek):
        backup = hooks / ("pre-commit.repro-local.backup-" + hashlib.sha256(preserved_before).hexdigest())
        if backup.is_symlink() or (backup.exists() and (
            not backup.is_file() or backup.read_bytes() != preserved_before
            or stat.S_IMODE(backup.stat().st_mode) != stat.S_IMODE(preserved.stat().st_mode)
        )):
            raise RuntimeError("unowned preserved-template backup")
    if not args.bootstrap_managed and set(original_pre_push) - {"pre-push.sample", "pre-push.repro-local"} != {"pre-push", "pre-push.repro-managed"}:
        raise RuntimeError("matching managed hooks must be established by ownership-checked caller bootstrap")
    push_before = original_pre_push.get("pre-push.repro-local")
    push_backup = None
    if push_before is not None and push_before[0] != canonical_body(prek, "pre-push"):
        push_backup = hooks / ("retired-owned-pre-push-local-" + hashlib.sha256(push_before[0]).hexdigest())
        if push_backup.is_symlink() or (push_backup.exists() and (
            not push_backup.is_file() or push_backup.read_bytes() != push_before[0]
            or stat.S_IMODE(push_backup.stat().st_mode) != push_before[1]
        )):
            raise RuntimeError("unowned former pre-push local backup")
    install_env = native_install_environment(env, git, root, hooks)
    # All ownership/refusal checks precede the first directory or hook write.
    hooks.mkdir(exist_ok=True)
    if repair_registered_relative_path:
        # Repair only the verified primary-owned local legacy setting after all checks.
        subprocess.run([git, "config", "--local", "core.hooksPath", str(hooks)], cwd=root, check=True)
        effective = Path(run([git, "rev-parse", "--path-format=absolute", "--git-path", "hooks"], root))
        if effective.is_symlink() or effective.resolve() != hooks:
            raise RuntimeError("registered worktree hook path repair did not select owning common hooks")
    if args.bootstrap_managed:
        # Separate caller bootstrap: every ownership check above completed before
        # matching ensure creates any hook. Preserve existing pre-push entries.
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        current_pre_push = pre_push_inventory(hooks, prek)
        expected_names = {"pre-push", "pre-push.repro-managed"} | (set(original_pre_push) & {"pre-push.sample", "pre-push.repro-local"})
        if set(current_pre_push) != expected_names:
            raise RuntimeError("matching bootstrap did not create qualified pre-push hooks")
        for name, snapshot in original_pre_push.items():
            if current_pre_push.get(name) != snapshot:
                raise RuntimeError(f"bootstrap changed existing pre-push body or mode: {name}")
        for name, expected_hash in KNOWN_MANAGED_BODIES.items():
            target = hooks / name
            if target.is_symlink() or not target.is_file() or stat.S_IMODE(target.stat().st_mode) != 0o755:
                raise RuntimeError(f"bootstrap produced unowned managed hook shape: {name}")
            if hashlib.sha256(target.read_bytes()).hexdigest() != expected_hash:
                raise RuntimeError(f"bootstrap produced unexpected managed hook body: {name}")
        local = hooks / "pre-commit.repro-local"
        if local.is_symlink() or (local.exists() and not local.is_file()):
            raise RuntimeError("bootstrap produced unowned preserved local hook shape")
        if local.exists():
            local_body = local.read_bytes()
            validate_prior_owned_body(local_body, stat.S_IMODE(local.stat().st_mode), prek)
            if preserved_before is not None and local_body != preserved_before:
                raise RuntimeError("bootstrap changed preserved local hook body")
        elif preserved_before is not None:
            raise RuntimeError("bootstrap removed preserved local hook")
        print("Ownership-checked matching managed bootstrap complete")
        return
    persisted_config = subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root)
    # Snapshot only the finite validated slots this migration owns.
    slots = ("pre-commit", "pre-commit.repro-local", "pre-push", "pre-push.repro-local")
    snapshots = {}
    for name in slots:
        path = hooks / name
        snapshots[name] = (path.read_bytes(), stat.S_IMODE(path.stat().st_mode)) if path.exists() else None
    success = False
    canonical = canonical_body(prek)
    canonical_push = canonical_body(prek, "pre-push")
    try:
        if backup is not None and not backup.exists():
            atomic_write(backup, preserved_before, 0o755)
        if push_backup is not None and not push_backup.exists():
            atomic_write(push_backup, push_before[0], push_before[1])
        # The genuine installer recognizes these exact qualified native bodies.
        # It therefore constructs both scripts without renaming managed dispatchers
        # to extra legacy hooks and without its overwrite option.
        for hook_type in ("pre-commit", "pre-push"):
            atomic_write(hooks / hook_type, native_generated_body(prek, hook_type), 0o755)
        native_install_to_terminal([prek, "install", "--install-hooks", "--hook-type", "pre-commit",
                                    "--hook-type", "pre-push"], root, install_env)
        for hook_type in ("pre-commit", "pre-push"):
            generated = hooks / hook_type
            if generated.is_symlink() or not generated.is_file():
                raise RuntimeError("actual generated hook is not owned regular file")
            body = canonical_generated_body(generated.read_bytes(), prek,
                                            stat.S_IMODE(generated.stat().st_mode), hook_type)
            local = hooks / (hook_type + ".repro-local")
            previous = snapshots[hook_type + ".repro-local"]
            if local.is_symlink() or (local.exists() and not local.is_file()):
                raise RuntimeError("preserved local hook changed shape during installation")
            observed = (local.read_bytes(), stat.S_IMODE(local.stat().st_mode)) if local.exists() else None
            if observed != previous:
                raise RuntimeError("preserved local hook changed during installation")
            atomic_write(generated, body, 0o755)
            atomic_write(local, body, 0o755)
        subprocess.run([str(repro), "hooks", "ensure", "--vcs", "."], cwd=root, env=env, check=True)
        expected_push = dict(original_pre_push)
        expected_push["pre-push.repro-local"] = (canonical_push, 0o755)
        if pre_push_inventory(hooks, prek) != expected_push:
            raise RuntimeError("unexpected pre-push migration inventory")
        for name, digest in KNOWN_MANAGED_BODIES.items():
            target = hooks / name
            if target.is_symlink() or not target.is_file() or stat.S_IMODE(target.stat().st_mode) != 0o755 or hashlib.sha256(target.read_bytes()).hexdigest() != digest:
                raise RuntimeError("migration changed qualified managed hook: " + name)
        success = True
    finally:
        if not success:
            for name, snapshot in snapshots.items():
                target = hooks / name
                if target.is_symlink() or (target.exists() and not target.is_file()):
                    raise RuntimeError("migration cleanup encountered unowned hook shape")
                if snapshot is None:
                    if target.exists():
                        target.unlink()
                else:
                    atomic_write(target, snapshot[0], snapshot[1])
            if pre_push_inventory(hooks, prek) != original_pre_push:
                raise RuntimeError("failed migration did not restore original pre-push inventory")
        if subprocess.check_output([git, "config", "--null", "--show-origin", "--list"], cwd=root) != persisted_config:
            raise RuntimeError("persisted Git configuration changed during native installation")
        for old_backup, expected in ((backup, None if preserved_before is None else (preserved_before, 0o755)),
                                    (push_backup, push_before)):
            if old_backup is not None and (
                old_backup.is_symlink() or not old_backup.is_file()
                or (old_backup.read_bytes(), stat.S_IMODE(old_backup.stat().st_mode)) != expected
            ):
                raise RuntimeError("qualified former hook backup changed")
    for hook_type, expected in (("pre-commit", canonical), ("pre-push", canonical_push)):
        local = hooks / (hook_type + ".repro-local")
        if local.is_symlink() or not local.is_file() or stat.S_IMODE(local.stat().st_mode) != 0o755 or local.read_bytes() != expected:
            raise RuntimeError("reconciled local hook did not preserve canonical native script")
    print("Canonical pinned commit and push hooks installed with preserved managed dispatchers")

if __name__ == "__main__":
    main()
